/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './google-maps.module';
import * as i2 from '@angular/common';
import * as i3 from './google-maps.service';
import * as i4 from './google-maps.class';
export const GoogleMapsModuleNgFactory:i0.NgModuleFactory<i1.GoogleMapsModule> = i0.ɵcmf(i1.GoogleMapsModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i3.GoogleMapsService,
          i3.GoogleMapsService,[[2,i4.UserServiceConfig]]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.GoogleMapsModule,i1.GoogleMapsModule,
          ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21lbHZpbnZhbmRlbmJlcmcvcHJvamVjdHMvYmFiYmxlci9nb29nbGUtbWFwcy1hbmd1bGFyMi9zcmMvYXBwL2dvb2dsZS1tYXBzLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9tZWx2aW52YW5kZW5iZXJnL3Byb2plY3RzL2JhYmJsZXIvZ29vZ2xlLW1hcHMtYW5ndWxhcjIvc3JjL2FwcC9nb29nbGUtbWFwcy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
